package cli

const (
	cliJSONKeyActor          = "actor"
	cliJSONKeyBackend        = "backend"
	cliJSONKeyBefore         = "before"
	cliJSONKeyChecks         = "checks"
	cliJSONKeyCommand        = "command"
	cliJSONKeyDaemonMetrics  = "daemon_metrics"
	cliJSONKeyError          = "error"
	cliJSONKeyErrors         = "errors"
	cliJSONKeyEvents         = "events"
	cliJSONKeyLocks          = "locks"
	cliJSONKeyMeasurements   = "measurements"
	cliJSONKeyMessage        = "message"
	cliJSONKeyMetrics        = "metrics"
	cliJSONKeyMonitorChanged = "monitor_changed_at"
	cliJSONKeyMonitorSource  = "monitor_source"
	cliJSONKeyMonitoring     = "monitoring"
	cliJSONKeyNotified       = "notified"
	cliJSONKeyOK             = "ok"
	cliJSONKeyPanic          = "panic"
	cliJSONKeyPanicChanged   = "panic_changed_at"
	cliJSONKeyPanicSource    = "panic_source"
	cliJSONKeyPatterns       = "patterns"
	cliJSONKeyPID            = "pid"
	cliJSONKeyProcesses      = "processes"
	cliJSONKeyPruned         = "pruned"
	cliJSONKeyRatio          = "ratio"
	cliJSONKeyScope          = "scope"
	cliJSONKeySeries         = "series"
	cliJSONKeyService        = "service"
	cliJSONKeyServiceMetrics = "service_metrics"
	cliJSONKeySince          = "since"
	cliJSONKeySLA            = "sla"
	cliJSONKeySource         = "source"
	cliJSONKeyState          = "state"
	cliJSONKeyStatus         = "status"
	cliJSONKeyStart          = "start"
	cliJSONKeyTarget         = "target"
	cliJSONKeyTime           = "time"
	cliJSONKeyTotal          = "total"
	cliJSONKeyUp             = "up"
	cliJSONKeyVacuum         = "vacuum"
	cliJSONKeyValid          = "valid"
	cliJSONKeyWatch          = "watch"
	cliJSONKeyWindows        = "windows"
)
